### PR TITLE
HRSPLT-249 : Add link in notice about open enrollment

### PR DESCRIPTION
**Pull request by timlevett**

### CODE REVIEW

**Comment by Doug-Reed** [comment]
:+1:

**Comment by jhanstra** [comment]
:+1:

**Comment by apetro** [comment]
:-1: . 
1. Looks like the link would show to both Madison and System users, but ought to show only to Madison users?
2. Should this change also be applied for the `enrollmentFlag == 'O'` div?

**Comment by timlevett** [comment]
Good catch @apetro , did hacky thing we talked about f2f, updated.

**Comment by vertein** [comment]
What's going on with this travis failure?  False error?

**Comment by vertein** [comment]
:+1: Failures caused by svn needing vpn

**Pull request merged**
