### PR TITLE
MUMUP-1305 : Update text in Benefit Information and UW System Benefit Information apps

### PR DESCRIPTION
**Pull request by Daha5**
https://jira.doit.wisc.edu/jira/browse/MUMUP-1305
Text change in Benefit Information portlet and UW System Benefit Information apps.

### CODE REVIEW

**Comment by apetro** [comment]
:+1: ; feedback: would prefer a more specific commit message that mentions `MUMUP-1305`.

**Comment by Daha5** [comment]
Noted. I'll be sure to do that in the future.

**Comment by timlevett** [comment]
:+1:

**Comment by vertein** [comment]
@Daha5, I'll show you next time you're in the office how to change your commit message if you remind me.

**Pull request merged**
