### PR TITLE
HRSPLT-215: Remove 'Coverage as of' text

### PR DESCRIPTION
**Pull request by jhanstra**
Just commenting out for now to retain the code if we decide to do [HRSPLT-226](https://jira.doit.wisc.edu/jira/browse/HRSPLT-226).

### CODE REVIEW

**Comment by apetro** [comment]
Thoughts:
1. Git means [never having to](https://en.wikipedia.org/wiki/Love_means_never_having_to_say_you%27re_sorry) comment out code that you don't need now but might want later. :smile: (It would be fine to go ahead and delete it, with a clear commit comment -- if we're looking for it later it'll be readily available in the history of the file, could even revert the commit to get exactly that code back.)
2. What if instead of deleting / commenting out the div, showing the div were predicated on `${coverageDate}`. That is, the underlying problem here is that `${coverageDate}` isn't being included in the data model fed to the JSP page.  When that's not in the model, the right thing to do is to just not say anything about the as-of date.  But if that were in the model, the right thing to do would be to reflect it in this div?

**Comment by apetro** [comment]
:+1:

**Comment by timlevett** [comment]
I would vote for just delete it.

**Comment by jhanstra** [comment]
Also in favor of deleting, I'll add a comment with this commit number.

**Comment by jhanstra** [comment]
Merging...

**Pull request merged**
